"use client"

import { useState } from "react"
import { ReferralLink } from "@/types/database"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { useToast } from "@/components/ui/use-toast"
import { Copy, RefreshCw, Loader2, ExternalLink } from "lucide-react"
import { useRouter } from "next/navigation"

interface ReferralLinksTabProps {
  initialLinks: ReferralLink[]
  userRole: string
}

export default function ReferralLinksTab({ initialLinks, userRole }: ReferralLinksTabProps) {
  const [links, setLinks] = useState<ReferralLink[]>(initialLinks)
  const [regenerating, setRegenerating] = useState<string | null>(null)
  const { toast } = useToast()
  const router = useRouter()

  const isAdmin = userRole === 'admin'

  const copyToClipboard = (slug: string) => {
    const url = `${window.location.origin}/r/${slug}`
    navigator.clipboard.writeText(url)
    toast({
      title: "Copied!",
      description: "Referral link copied to clipboard.",
    })
  }

  const handleRegenerate = async (userId: string, currentSlug: string) => {
    if (!confirm(`Are you sure you want to regenerate the referral link for this user? The old link (${currentSlug}) will no longer work.`)) {
      return
    }

    setRegenerating(userId)

    try {
      const response = await fetch('/api/referral-links/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ user_id: userId }),
      })

      const result = await response.json()

      if (!response.ok || !result.success) {
        throw new Error(result.error || 'Failed to regenerate link')
      }

      // Update the local state with the new link
      setLinks(links.map(link => 
        link.user_id === userId ? result.data : link
      ))

      toast({
        title: "Success!",
        description: "Referral link has been regenerated.",
      })

      // Refresh the page data
      router.refresh()

    } catch (error: any) {
      toast({
        variant: "destructive",
        title: "Error",
        description: error.message || "Failed to regenerate link.",
      })
    } finally {
      setRegenerating(null)
    }
  }

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })
  }

  const formatLastClick = (dateString: string | null | undefined) => {
    if (!dateString) return 'Never'
    
    const date = new Date(dateString)
    const now = new Date()
    const diffMs = now.getTime() - date.getTime()
    const diffMins = Math.floor(diffMs / 60000)
    const diffHours = Math.floor(diffMins / 60)
    const diffDays = Math.floor(diffHours / 24)

    if (diffMins < 1) return 'Just now'
    if (diffMins < 60) return `${diffMins}m ago`
    if (diffHours < 24) return `${diffHours}h ago`
    if (diffDays < 7) return `${diffDays}d ago`
    
    return formatDate(dateString)
  }

  if (links.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Referral Links</CardTitle>
          <CardDescription>
            {isAdmin 
              ? "No referral links have been created yet. Links are automatically generated when partner accounts are created."
              : "Your referral link will appear here once it's been generated by an administrator."}
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col items-center justify-center py-12 text-center">
          <p className="text-muted-foreground">No referral links available</p>
        </CardContent>
      </Card>
    )
  }

  return (
    <div className="space-y-4">
      <Card>
        <CardHeader>
          <CardTitle>Referral Links</CardTitle>
          <CardDescription>
            {isAdmin 
              ? "Manage partner referral links. Click the copy icon to copy a link or regenerate to create a new one."
              : "Share your unique referral link to track leads and earn commissions."}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Partner</TableHead>
                  <TableHead>Referral URL</TableHead>
                  <TableHead className="text-center">Clicks</TableHead>
                  <TableHead>Last Click</TableHead>
                  <TableHead>Created</TableHead>
                  <TableHead className="text-center">Status</TableHead>
                  {isAdmin && <TableHead className="text-right">Actions</TableHead>}
                </TableRow>
              </TableHeader>
              <TableBody>
                {links.map((link) => (
                  <TableRow key={link.id}>
                    <TableCell className="font-medium">
                      <div>
                        <div>{link.profiles?.name || 'Unknown'}</div>
                        {link.profiles?.handle && (
                          <div className="text-sm text-muted-foreground">
                            @{link.profiles.handle}
                          </div>
                        )}
                      </div>
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <code className="text-sm bg-muted px-2 py-1 rounded">
                          /r/{link.slug}
                        </code>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => copyToClipboard(link.slug)}
                          className="h-8 w-8 p-0"
                        >
                          <Copy className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => window.open(`/r/${link.slug}`, '_blank')}
                          className="h-8 w-8 p-0"
                        >
                          <ExternalLink className="h-4 w-4" />
                        </Button>
                      </div>
                    </TableCell>
                    <TableCell className="text-center">
                      <Badge variant="secondary">{link.click_count || 0}</Badge>
                    </TableCell>
                    <TableCell className="text-sm text-muted-foreground">
                      {formatLastClick(link.last_click_at)}
                    </TableCell>
                    <TableCell className="text-sm text-muted-foreground">
                      {formatDate(link.created_at)}
                    </TableCell>
                    <TableCell className="text-center">
                      {link.is_active ? (
                        <Badge variant="default">Active</Badge>
                      ) : (
                        <Badge variant="secondary">Inactive</Badge>
                      )}
                    </TableCell>
                    {isAdmin && (
                      <TableCell className="text-right">
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => handleRegenerate(link.user_id, link.slug)}
                          disabled={regenerating === link.user_id}
                        >
                          {regenerating === link.user_id ? (
                            <>
                              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                              Regenerating...
                            </>
                          ) : (
                            <>
                              <RefreshCw className="h-4 w-4 mr-2" />
                              Regenerate
                            </>
                          )}
                        </Button>
                      </TableCell>
                    )}
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>

      {!isAdmin && links.length > 0 && (
        <Card className="bg-muted/50">
          <CardHeader>
            <CardTitle className="text-base">How to Use Your Referral Link</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2 text-sm">
            <p>1. Copy your unique referral link using the copy button above</p>
            <p>2. Share it on your website, social media, business cards, or via email</p>
            <p>3. When homeowners click your link and submit a lead, it&apos;s automatically attributed to you</p>
            <p>4. Track your click count and last click time to monitor performance</p>
            <p className="text-muted-foreground italic mt-4">
              Note: If you need to change your referral link, please contact support.
            </p>
          </CardContent>
        </Card>
      )}
    </div>
  )
}

